### ISSUE TITLE
Anyone stil using this?

### ISSUE THREAD

**Issue by blademaster-888** [qiciengine/qiciengine#20]

**Comment by carlsmith** [comment]
Apparently not. It'd be nice to know if it was dropped because the code is a mess, or if it could be maintained by someone else.

**Comment by Triztan** [comment]
It's a promising project, would be really nice if it can get maintained by someone else

**Comment by Morabaraba** [comment]
> It'd be nice to know if it was dropped 

A google away [2016](http://www.html5gamedevs.com/topic/26264-qici-engine-dead/?tab=comments#comment-150326). But don't worry it is open source and anybody can take the examples, documents and engine and create the html5 game of their dreams...

> because the code is a mess,

Got any references or examples what needs in-proving, before making such negativity?

**Comment by carlsmith** [comment]
You misunderstood me. Sorry. I meant that *it would be nice to know **if** it was dropped because the code is a mess*, not that *it would be nice to know if it was dropped, **because** the code is a mess*.

The project looks pretty mature, so I wondered why it was dropped. Mature projects are normally maintained by somebody, just because there's normally a lot of value in mature projects and few people will start a project with abandoned libraries. I would of used this, but didn't because I don't want to maintain it, and it looks like no one else is going to.

**Comment by Morabaraba** [comment]
@carlsmith thanks for clearing that, I was also overzealous, so need to apologize as well.

> Mature projects are normally maintained by somebody,

As for qici it seems they moved onto another engine(lazer). qici is based on phaser 2.3(current v2.9) and they made changes to phaser 2.3 that makes it hard to upgrade, more info [in this comment](http://www.html5gamedevs.com/topic/19890-qici-engine-review/?tab=comments#comment-113145).

>  few people will start a project with abandoned libraries

True, and it saddens me because I like qici. I just hope everything gets nicely preserved on github for educational and historical purposes.

>  it looks like no one else is going to.

Yes it seems no-one at the moment have moved up to the plate to try and swing the bat.

#### hype and dev

Qici caught my eye at the end of its hype train. Gamedev is hard even with a tool and documentation like this. Its not the code, dragging or dropping that makes it hard/easy. Its the understanding of the entity model, component systems and how game objects/worlds interact.

Qici makes this a lot easier, but at a bit of a steep learning curve and you might need to be willing to use google translate for the Chinese.  

#### what I think the problem is/was

But I feel there a backstory with the first interaction on github, and I don't want to create something if there is nothing, so this might just be me taking crazy pills. 

The github community stepped a bit on toes by just decompiling the proprietary editor code. And without any other input suggesting the name needs to change... Im sticking to gamedev is HARD and even with a great engine, docs, examples, cookbooks it is still difficult to pickup if you don't have someone showing you the way.
